### ISSUE TITLE
Psiphon for Linux 的现代玩法

### ISSUE THREAD

**Issue by Peytonlan** [MewX/Psiphon3-for-Linux#10]
编译 Linux 客户端, 这块不细说了, 详见
https://github.com/Psiphon-Labs/psiphon-tunnel-core

初始数据哪儿来?
拷贝 Psiphon for Windows 的数据, 数据位于win下 %APPDATA%\Psiphon3

配置文件怎么改?
从win下拷贝过来的 Psiphon3 目录下有个 psiphon.config 配置文件, 以此为蓝本, 可用 jq 格式化后, 方便阅读编辑
```bash
jq <Psiphon3/psiphon.config '.' >psiphon.config.linux
```

**Comment by MewX** [comment]
谢谢，由 #11 跟踪
