### ISSUE TITLE
想知道要完全卸载应该怎么操作

### ISSUE THREAD

**Issue by Edge51** [MewX/Psiphon3-for-Linux#14]
貌似提供的两个文件中有makeinstall却没有makeuninstall,现在我想清理但是不知道怎么完全卸载他，我可能比较菜，可以的话帮帮忙谢谢啦

**Comment by MewX** [comment]
可能不得不自己手动删除文件了，

```
make -n install
```

应该可以列出所有拷贝的文件把对应文件删除应该就可以了

**Comment by Edge51** [comment]
啊好的谢谢～

**Comment by Edge51** [comment]
> 可能不得不自己手动删除文件了，
> 
> ```
> make -n install
> ```
> 
> 应该可以列出所有拷贝的文件把对应文件删除应该就可以了

啊好的谢谢～

**Comment by Edge51** [comment]
学习了一下make的使用，好像找到卸载方法了，打扰了，不好意思啊
