### ISSUE TITLE
compile ssh error

### ISSUE THREAD

**Issue by seedpower** [MewX/Psiphon3-for-Linux#2]
./configure
checking openssl/opensslv.h usability... no
checking openssl/opensslv.h presence... no
checking for openssl/opensslv.h... no
configure: error: **\* OpenSSL headers missing - please install first or check config.log ***

I have installed openssh in /usr/local/openssh
and installed ssh in /usr/local/ssh

Search from the Internet, I try to use these options,below
./configure --with-ssl-dir=/usr/local/openssh
./configure --with-ssl-dir=/usr/local/ssh
./configure --with-ssl-dir=/usr/local/openssh/include
but error always show!

How to solve it?

**Comment by MewX** [comment]
Try to install openssl-devel as well.

**Comment by seedpower** [comment]
yeah,solved it!

**Comment by luckypoem** [comment]
hi。

我运行./configure时，遇到错误：
configure: error: OpenSSL version header not found.
yudeMacBook-Air:openssh-5.9p1 brite$

我是在mac机子，运行brew install libssl-dev或者brew install  openssl-devel ,都提示没有相应的包。
如何解决这个问题呢？
非常感谢！

**Comment by MewX** [comment]
@luckypoem 
1. This repo is not maintained now;
2. Did you google it first? It's the problem on OpenSSL, so you'd better post this on StackOverflow after you searching for it.

**Comment by luckypoem** [comment]
hi.

搜了一下：
./configure  LDFLAGS=-L/usr/local/opt/openssl/lib CPPFLAGS=-I/usr/local/opt/openssl/include
这样，就不会遇错了。
然后make顺利生成了ssh文件。
cp openssh-5.9p1/ssh pyclient/
cd pyclient
python update.py

不过python update.py遇错：
yudeMacBook-Air:pyclient brite$ python update.py
--2016-09-20 21:41:35--  https://psiphon3.com/server_list
Resolving psiphon3.com... 200:2:cb62:741::
Connecting to psiphon3.com|200:2:cb62:741::|:443... failed: No route to host.
Traceback (most recent call last):
  File "update.py", line 14, in <module>
    dat["servers"] = json.load(open('server_list'))['data'].split()
IOError: [Errno 2] No such file or directory: 'server_list'
yudeMacBook-Air:pyclient brite$

如何解决呢？
谢谢你！

**Comment by MewX** [comment]
It seems you are using IPv6 and is not accessible to `psiphon3.com` through IPv6. (I guess)

So what you should do is to download the file `https://psiphon3.com/server_list` to the same directory with `update.py`, file name is `server_list`.

**Comment by luckypoem** [comment]
hi.

psiphon3.com域名被封，所以wget https://psiphon3.com/server_list是无果的，我是通过其他翻墙方式，下载https://psiphon3.com/server_list到pyclient/,
然后第一次运行python psi_client.py，遇到错误：
no such module: pexpect

于是运行sudo pip install pexpect
然后再次运行python psi_client.py
等了4-5分钟，终于出现：
Your SOCKS proxy is now running at 127.0.0.1:1080
Press Ctrl-C to terminate.

谢谢你的心血

**Comment by luckypoem** [comment]
不过难以连上服务器，还是放弃此方法。

**Comment by MewX** [comment]
@luckypoem 我还是推荐使用ss，你可以加入这个社区：
https://plus.google.com/communities/104092405342699579599
