### ISSUE TITLE
现在的OpenSSL的版本太高了 =。= 跟OpenSSH版本对应不上

### ISSUE THREAD

**Issue by Misng** [MewX/Psiphon3-for-Linux#6]
如题。

是否需要降低本地的OpenSSh的版本

> checking whether OpenSSL's headers match the library... no configure: 
error: Your OpenSSL headers do not match your library

**Comment by MewX** [comment]
降低本地openSSL版本

**Comment by MewX** [comment]
看能不能找到对应版本的openssl，然后加到这个项目里面
